### ISSUE TITLE
serverspec appears to do nothing. 

### ISSUE THREAD

**Issue by neilhwatson** [vvchik/vagrant-serverspec#28]
I've attached a set of files that create the output shown below. My expected result is a reported test failure ('NEVER PASSES').
t
[spec-test.zip](https://github.com/jvoorhis/vagrant-serverspec/files/372382/spec-test.zip)

```
neil@neptune ~/src/nextpathway/solr $ vagrant provision 
==> default: Running provisioner: serverspec...
<<< running helper

Command "java -version"
  stderr
Please set sudo password to Specinfra.configuration.sudo_password.

Finished in 0.24973 seconds (files took 1.68 seconds to load)
1 example, 0 failures

Finished in 0.24973 seconds (files took 1.68 seconds to load)
1 example, 0 failures

```

**Comment by lmayorga1980** [comment]
@neilhwatson ,

I noticed that you uploaded some data on your `spec_helper.rb` but you don't need to provide ssh configuration since its already handled for you. https://github.com/vvchik/vagrant-serverspec/blob/master/lib/vagrant-serverspec/provisioner.rb#L40-L62 

Are you trying to get a different behavior?

**Comment by neilhwatson** [comment]
So much time has passed I don't have the original files to reproduce this.
